source 'http://rubygems.org'

gem 'awesome_print'
gem 'diff-lcs',            '1.1.2'
gem 'factory_girl_rails'
gem 'haml'
gem 'haml-rails'
gem 'heroku'
gem 'hoptoad_notifier'
gem 'imagesize',           '0.1.1'
gem 'jquery-rails'
gem 'json'
gem 'omniauth'
gem 'rails',               '3.0.4'
gem 'rake',                '0.8.7'
gem 'recaptcha',           :require => 'recaptcha/rails'
gem 'rspec'
gem 'rspec-rails'
gem 'sass'
gem 'shoulda'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'taps',              '~> 0.3.22'
gem 'will_paginate',       '~> 3.0.pre2'
